name: run-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: checkout prebuilt binary
      run: ./checkout_prebuilt_binary_for_ci.sh ${{ secrets.RAFI_PREBUILT_BINARY_USER }} ${{ secrets.RAFI_PREBUILT_BINARY_ACCESS_TOKEN }}  
    - name: Run tests
      run: (export VERILATOR_ROOT=`pwd`/rafi-prebuilt-binary/verilator/Linux-x86_64 && export PATH=$PATH:$VERILATOR_ROOT/bin && sbt test)
